name: cleon-ai-landing

services:
  landing:
    build:
      context: .
    environment:
      PORT: ${PORT:-3002}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "${PORT:-3002}:${PORT:-3002}"
    networks:
      - cleon-net
    restart: always

networks:
  cleon-net:
    external: true
