name: cleon-ai

services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql

  backend:
    build:
      context: ../
      dockerfile: .docker/backend.Dockerfile 
    ports:
      - 3000:3000
    restart: always

volumes:
  postgres_data:
