name: cleon-ai-fe

services:
  frontend:
    build:
      context: ../
      dockerfile: .docker/frontend.Dockerfile 
    environment:
      PORT: ${PORT:-3001}
      NODE_ENV: ${NODE_ENV}
      VITE_FRONTEND_BASE_URL: ${VITE_FRONTEND_BASE_URL}
      VITE_API_URL: ${VITE_API_URL}
      VITE_LIVEKIT_WS_URL: ${VITE_LIVEKIT_WS_URL}
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    networks:
      - cleon-net
    restart: always

networks:
  cleon-net:
    external: true
