name: Deploy Landing

on:
  push:
    branches:
      - landing
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          set -e
          echo "⏳️ Deploy started.."

          cd ~/landing

          echo "📁 Pulling repository"
          git pull origin landing

          echo "📦 Building landing image"
          docker compose build

          echo "🔄 Starting service"
          docker compose up -d --remove-orphans

          echo "✅ Done."
